// Copyright (C) 2018 The Android Open Source Project
// Copyright (C) 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Autogenerated module goldfish_vk_reserved_marshaling_guest
//
// (header) generated by codegen/vulkan/vulkan-docs-next/scripts/genvk.py -registry
// codegen/vulkan/vulkan-docs-next/xml/vk.xml -registryGfxstream
// codegen/vulkan/vulkan-docs-next/xml/vk_gfxstream.xml cereal -o host/vulkan/cereal
//
// Please do not modify directly;
// re-run gfxstream-protocols/scripts/generate-vulkan-sources.sh,
// or directly from Python by defining:
// VULKAN_REGISTRY_XML_DIR : Directory containing vk.xml
// VULKAN_REGISTRY_SCRIPTS_DIR : Directory containing genvk.py
// CEREAL_OUTPUT_DIR: Where to put the generated sources.
//
// python3 $VULKAN_REGISTRY_SCRIPTS_DIR/genvk.py -registry $VULKAN_REGISTRY_XML_DIR/vk.xml cereal -o
// $CEREAL_OUTPUT_DIR
//
#pragma once
#include <vulkan/vulkan.h>

// #include "VulkanStreamGuest.h"
// #include "goldfish_vk_private_defs.h"
// #include "vk_android_native_buffer_gfxstream.h"
// #include "vk_platform_compat.h"
// #include "vulkan_gfxstream.h"

#include "express_vk_private_defs.h"
#include "express_vk_android_native_buffer_gfxstream.h"
#include "vk_platform_compat.h"
#include "vulkan_gfxstream.h"

// Stuff we are not going to use but if included,
// will cause compile errors. These are Android Vulkan
// required extensions, but the approach will be to
// implement them completely on the guest side.
#undef VK_KHR_android_surface
#undef VK_ANDROID_external_memory_android_hardware_buffer

#ifdef VK_VERSION_1_0
void encode_to_stream_VkExtent2D(VkStructureType rootType,
                                const VkExtent2D* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExtent3D(VkStructureType rootType,
                                const VkExtent3D* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkOffset2D(VkStructureType rootType,
                                const VkOffset2D* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkOffset3D(VkStructureType rootType,
                                const VkOffset3D* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRect2D(VkStructureType rootType,
                              const VkRect2D* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBaseInStructure(VkStructureType rootType,
                                       const VkBaseInStructure* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBaseOutStructure(VkStructureType rootType,
                                        const VkBaseOutStructure* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferMemoryBarrier(VkStructureType rootType,
                                           const VkBufferMemoryBarrier* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkDispatchIndirectCommand(
                                               VkStructureType rootType,
                                               const VkDispatchIndirectCommand* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkDrawIndexedIndirectCommand(
                                                  VkStructureType rootType,
                                                  const VkDrawIndexedIndirectCommand* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkDrawIndirectCommand(VkStructureType rootType,
                                           const VkDrawIndirectCommand* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkImageSubresourceRange(VkStructureType rootType,
                                             const VkImageSubresourceRange* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkImageMemoryBarrier(VkStructureType rootType,
                                          const VkImageMemoryBarrier* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryBarrier(VkStructureType rootType,
                                     const VkMemoryBarrier* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineCacheHeaderVersionOne(
    VkStructureType rootType,
    const VkPipelineCacheHeaderVersionOne* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkAllocationCallbacks(VkStructureType rootType,
                                           const VkAllocationCallbacks* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkApplicationInfo(VkStructureType rootType,
                                       const VkApplicationInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkFormatProperties(VkStructureType rootType,
                                        const VkFormatProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageFormatProperties(VkStructureType rootType,
                                             const VkImageFormatProperties* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkInstanceCreateInfo(VkStructureType rootType,
                                          const VkInstanceCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryHeap(VkStructureType rootType,
                                  const VkMemoryHeap* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryType(VkStructureType rootType,
                                  const VkMemoryType* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceFeatures(VkStructureType rootType,
                                              const VkPhysicalDeviceFeatures* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceLimits(VkStructureType rootType,
                                            const VkPhysicalDeviceLimits* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMemoryProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceMemoryProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSparseProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceSparseProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceProperties(
                                                VkStructureType rootType,
                                                const VkPhysicalDeviceProperties* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkQueueFamilyProperties(VkStructureType rootType,
                                             const VkQueueFamilyProperties* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkDeviceQueueCreateInfo(VkStructureType rootType,
                                             const VkDeviceQueueCreateInfo* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkDeviceCreateInfo(VkStructureType rootType,
                                        const VkDeviceCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExtensionProperties(VkStructureType rootType,
                                           const VkExtensionProperties* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkLayerProperties(VkStructureType rootType,
                                       const VkLayerProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubmitInfo(VkStructureType rootType,
                                  const VkSubmitInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMappedMemoryRange(VkStructureType rootType,
                                         const VkMappedMemoryRange* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryAllocateInfo(VkStructureType rootType,
                                          const VkMemoryAllocateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryRequirements(VkStructureType rootType,
                                          const VkMemoryRequirements* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSparseMemoryBind(VkStructureType rootType,
                                        const VkSparseMemoryBind* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSparseBufferMemoryBindInfo(
                                                  VkStructureType rootType,
                                                  const VkSparseBufferMemoryBindInfo* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkSparseImageOpaqueMemoryBindInfo(
    VkStructureType rootType,
    const VkSparseImageOpaqueMemoryBindInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageSubresource(VkStructureType rootType,
                                        const VkImageSubresource* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSparseImageMemoryBind(VkStructureType rootType,
                                             const VkSparseImageMemoryBind* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkSparseImageMemoryBindInfo(
                                                 VkStructureType rootType,
                                                 const VkSparseImageMemoryBindInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkBindSparseInfo(VkStructureType rootType,
                                      const VkBindSparseInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSparseImageFormatProperties(
    VkStructureType rootType,
    const VkSparseImageFormatProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSparseImageMemoryRequirements(
    VkStructureType rootType,
    const VkSparseImageMemoryRequirements* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkFenceCreateInfo(VkStructureType rootType,
                                       const VkFenceCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSemaphoreCreateInfo(VkStructureType rootType,
                                           const VkSemaphoreCreateInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkEventCreateInfo(VkStructureType rootType,
                                       const VkEventCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkQueryPoolCreateInfo(VkStructureType rootType,
                                           const VkQueryPoolCreateInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkBufferCreateInfo(VkStructureType rootType,
                                        const VkBufferCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferViewCreateInfo(VkStructureType rootType,
                                            const VkBufferViewCreateInfo* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkImageCreateInfo(VkStructureType rootType,
                                       const VkImageCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubresourceLayout(VkStructureType rootType,
                                         const VkSubresourceLayout* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkComponentMapping(VkStructureType rootType,
                                        const VkComponentMapping* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageViewCreateInfo(VkStructureType rootType,
                                           const VkImageViewCreateInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkShaderModuleCreateInfo(VkStructureType rootType,
                                              const VkShaderModuleCreateInfo* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkPipelineCacheCreateInfo(
                                               VkStructureType rootType,
                                               const VkPipelineCacheCreateInfo* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkSpecializationMapEntry(VkStructureType rootType,
                                              const VkSpecializationMapEntry* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkSpecializationInfo(VkStructureType rootType,
                                          const VkSpecializationInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineShaderStageCreateInfo(
    VkStructureType rootType,
    const VkPipelineShaderStageCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkComputePipelineCreateInfo(
                                                 VkStructureType rootType,
                                                 const VkComputePipelineCreateInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkVertexInputBindingDescription(
    VkStructureType rootType,
    const VkVertexInputBindingDescription* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkVertexInputAttributeDescription(
    VkStructureType rootType,
    const VkVertexInputAttributeDescription* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineVertexInputStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineVertexInputStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineInputAssemblyStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineInputAssemblyStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineTessellationStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineTessellationStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkViewport(VkStructureType rootType,
                                const VkViewport* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineViewportStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineViewportStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineRasterizationStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineRasterizationStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineMultisampleStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineMultisampleStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkStencilOpState(VkStructureType rootType,
                                      const VkStencilOpState* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineDepthStencilStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineDepthStencilStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineColorBlendAttachmentState(
    VkStructureType rootType,
    const VkPipelineColorBlendAttachmentState* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineColorBlendStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineColorBlendStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineDynamicStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineDynamicStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkGraphicsPipelineCreateInfo(
                                                  VkStructureType rootType,
                                                  const VkGraphicsPipelineCreateInfo* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkPushConstantRange(VkStructureType rootType,
                                         const VkPushConstantRange* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineLayoutCreateInfo(
                                                VkStructureType rootType,
                                                const VkPipelineLayoutCreateInfo* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkSamplerCreateInfo(VkStructureType rootType,
                                         const VkSamplerCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCopyDescriptorSet(VkStructureType rootType,
                                         const VkCopyDescriptorSet* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorBufferInfo(VkStructureType rootType,
                                            const VkDescriptorBufferInfo* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkDescriptorImageInfo(VkStructureType rootType,
                                           const VkDescriptorImageInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkDescriptorPoolSize(VkStructureType rootType,
                                          const VkDescriptorPoolSize* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorPoolCreateInfo(
                                                VkStructureType rootType,
                                                const VkDescriptorPoolCreateInfo* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkDescriptorSetAllocateInfo(
                                                 VkStructureType rootType,
                                                 const VkDescriptorSetAllocateInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkDescriptorSetLayoutBinding(
                                                  VkStructureType rootType,
                                                  const VkDescriptorSetLayoutBinding* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkDescriptorSetLayoutCreateInfo(
    VkStructureType rootType,
    const VkDescriptorSetLayoutCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkWriteDescriptorSet(VkStructureType rootType,
                                          const VkWriteDescriptorSet* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkAttachmentDescription(VkStructureType rootType,
                                             const VkAttachmentDescription* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkAttachmentReference(VkStructureType rootType,
                                           const VkAttachmentReference* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkFramebufferCreateInfo(VkStructureType rootType,
                                             const VkFramebufferCreateInfo* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkSubpassDescription(VkStructureType rootType,
                                          const VkSubpassDescription* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubpassDependency(VkStructureType rootType,
                                         const VkSubpassDependency* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassCreateInfo(VkStructureType rootType,
                                            const VkRenderPassCreateInfo* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkCommandPoolCreateInfo(VkStructureType rootType,
                                             const VkCommandPoolCreateInfo* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkCommandBufferAllocateInfo(
                                                 VkStructureType rootType,
                                                 const VkCommandBufferAllocateInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkCommandBufferInheritanceInfo(
    VkStructureType rootType,
    const VkCommandBufferInheritanceInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCommandBufferBeginInfo(VkStructureType rootType,
                                              const VkCommandBufferBeginInfo* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkBufferCopy(VkStructureType rootType,
                                  const VkBufferCopy* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageSubresourceLayers(VkStructureType rootType,
                                              const VkImageSubresourceLayers* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkBufferImageCopy(VkStructureType rootType,
                                       const VkBufferImageCopy* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkClearColorValue(VkStructureType rootType,
                                       const VkClearColorValue* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkClearDepthStencilValue(VkStructureType rootType,
                                              const VkClearDepthStencilValue* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkClearValue(VkStructureType rootType,
                                  const VkClearValue* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkClearAttachment(VkStructureType rootType,
                                       const VkClearAttachment* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkClearRect(VkStructureType rootType,
                                 const VkClearRect* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageBlit(VkStructureType rootType,
                                 const VkImageBlit* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageCopy(VkStructureType rootType,
                                 const VkImageCopy* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageResolve(VkStructureType rootType,
                                    const VkImageResolve* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassBeginInfo(VkStructureType rootType,
                                           const VkRenderPassBeginInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkPresentInfoKHR(VkStructureType rootType,
                                      const VkPresentInfoKHR* forMarshaling, uint8_t** ptr);                                           

#endif
#ifdef VK_VERSION_1_1
void encode_to_stream_VkPhysicalDeviceSubgroupProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceSubgroupProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBindBufferMemoryInfo(VkStructureType rootType,
                                            const VkBindBufferMemoryInfo* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkBindImageMemoryInfo(VkStructureType rootType,
                                           const VkBindImageMemoryInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkPhysicalDevice16BitStorageFeatures(
    VkStructureType rootType,
    const VkPhysicalDevice16BitStorageFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryDedicatedRequirements(
    VkStructureType rootType,
    const VkMemoryDedicatedRequirements* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryDedicatedAllocateInfo(
    VkStructureType rootType,
    const VkMemoryDedicatedAllocateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryAllocateFlagsInfo(
                                               VkStructureType rootType,
                                               const VkMemoryAllocateFlagsInfo* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkDeviceGroupRenderPassBeginInfo(
    VkStructureType rootType,
    const VkDeviceGroupRenderPassBeginInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceGroupCommandBufferBeginInfo(
    VkStructureType rootType,
    const VkDeviceGroupCommandBufferBeginInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceGroupSubmitInfo(VkStructureType rootType,
                                             const VkDeviceGroupSubmitInfo* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkDeviceGroupBindSparseInfo(
                                                 VkStructureType rootType,
                                                 const VkDeviceGroupBindSparseInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkBindBufferMemoryDeviceGroupInfo(
    VkStructureType rootType,
    const VkBindBufferMemoryDeviceGroupInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBindImageMemoryDeviceGroupInfo(
    VkStructureType rootType,
    const VkBindImageMemoryDeviceGroupInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceGroupProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceGroupProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceGroupDeviceCreateInfo(
    VkStructureType rootType,
    const VkDeviceGroupDeviceCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferMemoryRequirementsInfo2(
    VkStructureType rootType,
    const VkBufferMemoryRequirementsInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageMemoryRequirementsInfo2(
    VkStructureType rootType,
    const VkImageMemoryRequirementsInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageSparseMemoryRequirementsInfo2(
    VkStructureType rootType,
    const VkImageSparseMemoryRequirementsInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryRequirements2(VkStructureType rootType,
                                           const VkMemoryRequirements2* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkSparseImageMemoryRequirements2(
    VkStructureType rootType,
    const VkSparseImageMemoryRequirements2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceFeatures2(
                                               VkStructureType rootType,
                                               const VkPhysicalDeviceFeatures2* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceProperties2(
                                                 VkStructureType rootType,
                                                 const VkPhysicalDeviceProperties2* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkFormatProperties2(VkStructureType rootType,
                                         const VkFormatProperties2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageFormatProperties2(VkStructureType rootType,
                                              const VkImageFormatProperties2* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceImageFormatInfo2(
    VkStructureType rootType,
    const VkPhysicalDeviceImageFormatInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkQueueFamilyProperties2(VkStructureType rootType,
                                              const VkQueueFamilyProperties2* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMemoryProperties2(
    VkStructureType rootType,
    const VkPhysicalDeviceMemoryProperties2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSparseImageFormatProperties2(
    VkStructureType rootType,
    const VkSparseImageFormatProperties2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSparseImageFormatInfo2(
    VkStructureType rootType,
    const VkPhysicalDeviceSparseImageFormatInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDevicePointClippingProperties(
    VkStructureType rootType,
    const VkPhysicalDevicePointClippingProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkInputAttachmentAspectReference(
    VkStructureType rootType,
    const VkInputAttachmentAspectReference* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassInputAttachmentAspectCreateInfo(
    VkStructureType rootType,
    const VkRenderPassInputAttachmentAspectCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageViewUsageCreateInfo(
                                                VkStructureType rootType,
                                                const VkImageViewUsageCreateInfo* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkPipelineTessellationDomainOriginStateCreateInfo(
    VkStructureType rootType,
    const VkPipelineTessellationDomainOriginStateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassMultiviewCreateInfo(
    VkStructureType rootType,
    const VkRenderPassMultiviewCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMultiviewFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceMultiviewFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMultiviewProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceMultiviewProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVariablePointersFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceVariablePointersFeatures* forMarshaling, uint8_t** ptr);

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceVariablePointersFeatures,
                      encode_to_stream_VkPhysicalDeviceVariablePointerFeatures)

void encode_to_stream_VkPhysicalDeviceProtectedMemoryFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceProtectedMemoryFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceProtectedMemoryProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceProtectedMemoryProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceQueueInfo2(VkStructureType rootType,
                                        const VkDeviceQueueInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkProtectedSubmitInfo(VkStructureType rootType,
                                           const VkProtectedSubmitInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkSamplerYcbcrConversionCreateInfo(
    VkStructureType rootType,
    const VkSamplerYcbcrConversionCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSamplerYcbcrConversionInfo(
                                                  VkStructureType rootType,
                                                  const VkSamplerYcbcrConversionInfo* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkBindImagePlaneMemoryInfo(
                                                VkStructureType rootType,
                                                const VkBindImagePlaneMemoryInfo* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkImagePlaneMemoryRequirementsInfo(
    VkStructureType rootType,
    const VkImagePlaneMemoryRequirementsInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSamplerYcbcrConversionFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceSamplerYcbcrConversionFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSamplerYcbcrConversionImageFormatProperties(
    VkStructureType rootType,
    const VkSamplerYcbcrConversionImageFormatProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorUpdateTemplateEntry(
    VkStructureType rootType,
    const VkDescriptorUpdateTemplateEntry* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorUpdateTemplateCreateInfo(
    VkStructureType rootType,
    const VkDescriptorUpdateTemplateCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExternalMemoryProperties(
                                                VkStructureType rootType,
                                                const VkExternalMemoryProperties* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceExternalImageFormatInfo(
    VkStructureType rootType,
    const VkPhysicalDeviceExternalImageFormatInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExternalImageFormatProperties(
    VkStructureType rootType,
    const VkExternalImageFormatProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceExternalBufferInfo(
    VkStructureType rootType,
    const VkPhysicalDeviceExternalBufferInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExternalBufferProperties(
                                                VkStructureType rootType,
                                                const VkExternalBufferProperties* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceIDProperties(
                                                  VkStructureType rootType,
                                                  const VkPhysicalDeviceIDProperties* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkExternalMemoryImageCreateInfo(
    VkStructureType rootType,
    const VkExternalMemoryImageCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExternalMemoryBufferCreateInfo(
    VkStructureType rootType,
    const VkExternalMemoryBufferCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExportMemoryAllocateInfo(
                                                VkStructureType rootType,
                                                const VkExportMemoryAllocateInfo* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceExternalFenceInfo(
    VkStructureType rootType,
    const VkPhysicalDeviceExternalFenceInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExternalFenceProperties(
                                               VkStructureType rootType,
                                               const VkExternalFenceProperties* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkExportFenceCreateInfo(VkStructureType rootType,
                                             const VkExportFenceCreateInfo* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkExportSemaphoreCreateInfo(
                                                 VkStructureType rootType,
                                                 const VkExportSemaphoreCreateInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceExternalSemaphoreInfo(
    VkStructureType rootType,
    const VkPhysicalDeviceExternalSemaphoreInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkExternalSemaphoreProperties(
    VkStructureType rootType,
    const VkExternalSemaphoreProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMaintenance3Properties(
    VkStructureType rootType,
    const VkPhysicalDeviceMaintenance3Properties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorSetLayoutSupport(
                                                  VkStructureType rootType,
                                                  const VkDescriptorSetLayoutSupport* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderDrawParametersFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderDrawParametersFeatures* forMarshaling, uint8_t** ptr);

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderDrawParametersFeatures,
                      encode_to_stream_VkPhysicalDeviceShaderDrawParameterFeatures)

#endif
#ifdef VK_VERSION_1_2
void encode_to_stream_VkPhysicalDeviceVulkan11Features(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkan11Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVulkan11Properties(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkan11Properties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVulkan12Features(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkan12Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkConformanceVersion(VkStructureType rootType,
                                          const VkConformanceVersion* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVulkan12Properties(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkan12Properties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageFormatListCreateInfo(
                                                 VkStructureType rootType,
                                                 const VkImageFormatListCreateInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkAttachmentDescription2(VkStructureType rootType,
                                              const VkAttachmentDescription2* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkAttachmentReference2(VkStructureType rootType,
                                            const VkAttachmentReference2* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkSubpassDescription2(VkStructureType rootType,
                                           const VkSubpassDescription2* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkSubpassDependency2(VkStructureType rootType,
                                          const VkSubpassDependency2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassCreateInfo2(VkStructureType rootType,
                                             const VkRenderPassCreateInfo2* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkSubpassBeginInfo(VkStructureType rootType,
                                        const VkSubpassBeginInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubpassEndInfo(VkStructureType rootType,
                                      const VkSubpassEndInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDevice8BitStorageFeatures(
    VkStructureType rootType,
    const VkPhysicalDevice8BitStorageFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceDriverProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceDriverProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderAtomicInt64Features(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderAtomicInt64Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderFloat16Int8Features(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderFloat16Int8Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceFloatControlsProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceFloatControlsProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorSetLayoutBindingFlagsCreateInfo(
    VkStructureType rootType,
    const VkDescriptorSetLayoutBindingFlagsCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceDescriptorIndexingFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceDescriptorIndexingFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceDescriptorIndexingProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceDescriptorIndexingProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorSetVariableDescriptorCountAllocateInfo(
    VkStructureType rootType,
    const VkDescriptorSetVariableDescriptorCountAllocateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorSetVariableDescriptorCountLayoutSupport(
    VkStructureType rootType,
    const VkDescriptorSetVariableDescriptorCountLayoutSupport* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubpassDescriptionDepthStencilResolve(
    VkStructureType rootType,
    const VkSubpassDescriptionDepthStencilResolve* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceDepthStencilResolveProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceDepthStencilResolveProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceScalarBlockLayoutFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceScalarBlockLayoutFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageStencilUsageCreateInfo(
    VkStructureType rootType,
    const VkImageStencilUsageCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSamplerReductionModeCreateInfo(
    VkStructureType rootType,
    const VkSamplerReductionModeCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSamplerFilterMinmaxProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceSamplerFilterMinmaxProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVulkanMemoryModelFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkanMemoryModelFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceImagelessFramebufferFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceImagelessFramebufferFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkFramebufferAttachmentImageInfo(
    VkStructureType rootType,
    const VkFramebufferAttachmentImageInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkFramebufferAttachmentsCreateInfo(
    VkStructureType rootType,
    const VkFramebufferAttachmentsCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassAttachmentBeginInfo(
    VkStructureType rootType,
    const VkRenderPassAttachmentBeginInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceUniformBufferStandardLayoutFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceUniformBufferStandardLayoutFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceSeparateDepthStencilLayoutsFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkAttachmentReferenceStencilLayout(
    VkStructureType rootType,
    const VkAttachmentReferenceStencilLayout* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkAttachmentDescriptionStencilLayout(
    VkStructureType rootType,
    const VkAttachmentDescriptionStencilLayout* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceHostQueryResetFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceHostQueryResetFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceTimelineSemaphoreFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceTimelineSemaphoreFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceTimelineSemaphoreProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceTimelineSemaphoreProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSemaphoreTypeCreateInfo(
                                               VkStructureType rootType,
                                               const VkSemaphoreTypeCreateInfo* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkTimelineSemaphoreSubmitInfo(
    VkStructureType rootType,
    const VkTimelineSemaphoreSubmitInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSemaphoreWaitInfo(VkStructureType rootType,
                                         const VkSemaphoreWaitInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSemaphoreSignalInfo(VkStructureType rootType,
                                           const VkSemaphoreSignalInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceBufferDeviceAddressFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceBufferDeviceAddressFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferDeviceAddressInfo(
                                               VkStructureType rootType,
                                               const VkBufferDeviceAddressInfo* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkBufferOpaqueCaptureAddressCreateInfo(
    VkStructureType rootType,
    const VkBufferOpaqueCaptureAddressCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryOpaqueCaptureAddressAllocateInfo(
    VkStructureType rootType,
    const VkMemoryOpaqueCaptureAddressAllocateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceMemoryOpaqueCaptureAddressInfo(
    VkStructureType rootType,
    const VkDeviceMemoryOpaqueCaptureAddressInfo* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_VERSION_1_3
void encode_to_stream_VkPhysicalDeviceVulkan13Features(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkan13Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVulkan13Properties(
    VkStructureType rootType,
    const VkPhysicalDeviceVulkan13Properties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineCreationFeedback(
                                                VkStructureType rootType,
                                                const VkPipelineCreationFeedback* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkPipelineCreationFeedbackCreateInfo(
    VkStructureType rootType,
    const VkPipelineCreationFeedbackCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderTerminateInvocationFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderTerminateInvocationFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceToolProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceToolProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDevicePrivateDataFeatures(
    VkStructureType rootType,
    const VkPhysicalDevicePrivateDataFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDevicePrivateDataCreateInfo(
    VkStructureType rootType,
    const VkDevicePrivateDataCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPrivateDataSlotCreateInfo(
                                                 VkStructureType rootType,
                                                 const VkPrivateDataSlotCreateInfo* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkPhysicalDevicePipelineCreationCacheControlFeatures(
    VkStructureType rootType,
    const VkPhysicalDevicePipelineCreationCacheControlFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryBarrier2(VkStructureType rootType,
                                      const VkMemoryBarrier2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferMemoryBarrier2(VkStructureType rootType,
                                            const VkBufferMemoryBarrier2* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkImageMemoryBarrier2(VkStructureType rootType,
                                           const VkImageMemoryBarrier2* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkDependencyInfo(VkStructureType rootType,
                                      const VkDependencyInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSemaphoreSubmitInfo(VkStructureType rootType,
                                           const VkSemaphoreSubmitInfo* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkCommandBufferSubmitInfo(
                                               VkStructureType rootType,
                                               const VkCommandBufferSubmitInfo* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkSubmitInfo2(VkStructureType rootType,
                                   const VkSubmitInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSynchronization2Features(
    VkStructureType rootType,
    const VkPhysicalDeviceSynchronization2Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceImageRobustnessFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceImageRobustnessFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferCopy2(VkStructureType rootType,
                                   const VkBufferCopy2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCopyBufferInfo2(VkStructureType rootType,
                                       const VkCopyBufferInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageCopy2(VkStructureType rootType,
                                  const VkImageCopy2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCopyImageInfo2(VkStructureType rootType,
                                      const VkCopyImageInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferImageCopy2(VkStructureType rootType,
                                        const VkBufferImageCopy2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCopyBufferToImageInfo2(VkStructureType rootType,
                                              const VkCopyBufferToImageInfo2* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkCopyImageToBufferInfo2(VkStructureType rootType,
                                              const VkCopyImageToBufferInfo2* forMarshaling,
                                              uint8_t** ptr);

void encode_to_stream_VkImageBlit2(VkStructureType rootType,
                                  const VkImageBlit2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBlitImageInfo2(VkStructureType rootType,
                                      const VkBlitImageInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageResolve2(VkStructureType rootType,
                                     const VkImageResolve2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkResolveImageInfo2(VkStructureType rootType,
                                         const VkResolveImageInfo2* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSubgroupSizeControlFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceSubgroupSizeControlFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceSubgroupSizeControlProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceSubgroupSizeControlProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineShaderStageRequiredSubgroupSizeCreateInfo(
    VkStructureType rootType,
    const VkPipelineShaderStageRequiredSubgroupSizeCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceInlineUniformBlockFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceInlineUniformBlockFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceInlineUniformBlockProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceInlineUniformBlockProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkWriteDescriptorSetInlineUniformBlock(
    VkStructureType rootType,
    const VkWriteDescriptorSetInlineUniformBlock* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDescriptorPoolInlineUniformBlockCreateInfo(
    VkStructureType rootType,
    const VkDescriptorPoolInlineUniformBlockCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceTextureCompressionASTCHDRFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceTextureCompressionASTCHDRFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderingAttachmentInfo(
                                               VkStructureType rootType,
                                               const VkRenderingAttachmentInfo* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkRenderingInfo(VkStructureType rootType,
                                     const VkRenderingInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineRenderingCreateInfo(
    VkStructureType rootType,
    const VkPipelineRenderingCreateInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceDynamicRenderingFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceDynamicRenderingFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCommandBufferInheritanceRenderingInfo(
    VkStructureType rootType,
    const VkCommandBufferInheritanceRenderingInfo* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderIntegerDotProductFeatures(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderIntegerDotProductFeatures* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceShaderIntegerDotProductProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceShaderIntegerDotProductProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceTexelBufferAlignmentProperties(
    VkStructureType rootType,
    const VkPhysicalDeviceTexelBufferAlignmentProperties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkFormatProperties3(VkStructureType rootType,
                                         const VkFormatProperties3* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMaintenance4Features(
    VkStructureType rootType,
    const VkPhysicalDeviceMaintenance4Features* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMaintenance4Properties(
    VkStructureType rootType,
    const VkPhysicalDeviceMaintenance4Properties* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceBufferMemoryRequirements(
    VkStructureType rootType,
    const VkDeviceBufferMemoryRequirements* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceImageMemoryRequirements(
    VkStructureType rootType,
    const VkDeviceImageMemoryRequirements* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_dynamic_rendering
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkRenderingInfo, encode_to_stream_VkRenderingInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkRenderingAttachmentInfo,
                      encode_to_stream_VkRenderingAttachmentInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPipelineRenderingCreateInfo,
                      encode_to_stream_VkPipelineRenderingCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceDynamicRenderingFeatures,
                      encode_to_stream_VkPhysicalDeviceDynamicRenderingFeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkCommandBufferInheritanceRenderingInfo,
                      encode_to_stream_VkCommandBufferInheritanceRenderingInfoKHR)

void encode_to_stream_VkRenderingFragmentShadingRateAttachmentInfoKHR(
    VkStructureType rootType,
    const VkRenderingFragmentShadingRateAttachmentInfoKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderingFragmentDensityMapAttachmentInfoEXT(
    VkStructureType rootType,
    const VkRenderingFragmentDensityMapAttachmentInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkAttachmentSampleCountInfoAMD(
    VkStructureType rootType,
    const VkAttachmentSampleCountInfoAMD* forMarshaling, uint8_t** ptr);

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkAttachmentSampleCountInfoAMD,
                      encode_to_stream_VkAttachmentSampleCountInfoNV)

void encode_to_stream_VkMultiviewPerViewAttributesInfoNVX(
    VkStructureType rootType,
    const VkMultiviewPerViewAttributesInfoNVX* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_get_physical_device_properties2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceFeatures2,
                      encode_to_stream_VkPhysicalDeviceFeatures2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceProperties2,
                      encode_to_stream_VkPhysicalDeviceProperties2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkFormatProperties2, encode_to_stream_VkFormatProperties2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageFormatProperties2,
                      encode_to_stream_VkImageFormatProperties2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceImageFormatInfo2,
                      encode_to_stream_VkPhysicalDeviceImageFormatInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkQueueFamilyProperties2,
                      encode_to_stream_VkQueueFamilyProperties2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceMemoryProperties2,
                      encode_to_stream_VkPhysicalDeviceMemoryProperties2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSparseImageFormatProperties2,
                      encode_to_stream_VkSparseImageFormatProperties2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceSparseImageFormatInfo2,
                      encode_to_stream_VkPhysicalDeviceSparseImageFormatInfo2KHR)

#endif
#ifdef VK_KHR_external_memory_capabilities
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalMemoryProperties,
                      encode_to_stream_VkExternalMemoryPropertiesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceExternalImageFormatInfo,
                      encode_to_stream_VkPhysicalDeviceExternalImageFormatInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalImageFormatProperties,
                      encode_to_stream_VkExternalImageFormatPropertiesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceExternalBufferInfo,
                      encode_to_stream_VkPhysicalDeviceExternalBufferInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalBufferProperties,
                      encode_to_stream_VkExternalBufferPropertiesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceIDProperties,
                      encode_to_stream_VkPhysicalDeviceIDPropertiesKHR)

#endif
#ifdef VK_KHR_external_memory
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalMemoryImageCreateInfo,
                      encode_to_stream_VkExternalMemoryImageCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalMemoryBufferCreateInfo,
                      encode_to_stream_VkExternalMemoryBufferCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExportMemoryAllocateInfo,
                      encode_to_stream_VkExportMemoryAllocateInfoKHR)

#endif
#ifdef VK_KHR_external_semaphore_capabilities
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceExternalSemaphoreInfo,
                      encode_to_stream_VkPhysicalDeviceExternalSemaphoreInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalSemaphoreProperties,
                      encode_to_stream_VkExternalSemaphorePropertiesKHR)

#endif
#ifdef VK_KHR_external_semaphore
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExportSemaphoreCreateInfo,
                      encode_to_stream_VkExportSemaphoreCreateInfoKHR)

#endif
#ifdef VK_KHR_external_semaphore_fd
void encode_to_stream_VkImportSemaphoreFdInfoKHR(
                                                VkStructureType rootType,
                                                const VkImportSemaphoreFdInfoKHR* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkSemaphoreGetFdInfoKHR(VkStructureType rootType,
                                             const VkSemaphoreGetFdInfoKHR* forMarshaling,
                                             uint8_t** ptr);

#endif
#ifdef VK_KHR_shader_float16_int8
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderFloat16Int8Features,
                      encode_to_stream_VkPhysicalDeviceShaderFloat16Int8FeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderFloat16Int8Features,
                      encode_to_stream_VkPhysicalDeviceFloat16Int8FeaturesKHR)

#endif
#ifdef VK_KHR_incremental_present
void encode_to_stream_VkRectLayerKHR(VkStructureType rootType,
                                    const VkRectLayerKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPresentRegionKHR(VkStructureType rootType,
                                        const VkPresentRegionKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPresentRegionsKHR(VkStructureType rootType,
                                         const VkPresentRegionsKHR* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_descriptor_update_template
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDescriptorUpdateTemplateEntry,
                      encode_to_stream_VkDescriptorUpdateTemplateEntryKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDescriptorUpdateTemplateCreateInfo,
                      encode_to_stream_VkDescriptorUpdateTemplateCreateInfoKHR)

#endif
#ifdef VK_KHR_imageless_framebuffer
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceImagelessFramebufferFeatures,
                      encode_to_stream_VkPhysicalDeviceImagelessFramebufferFeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkFramebufferAttachmentsCreateInfo,
                      encode_to_stream_VkFramebufferAttachmentsCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkFramebufferAttachmentImageInfo,
                      encode_to_stream_VkFramebufferAttachmentImageInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkRenderPassAttachmentBeginInfo,
                      encode_to_stream_VkRenderPassAttachmentBeginInfoKHR)

#endif
#ifdef VK_KHR_create_renderpass2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkRenderPassCreateInfo2,
                      encode_to_stream_VkRenderPassCreateInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkAttachmentDescription2,
                      encode_to_stream_VkAttachmentDescription2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkAttachmentReference2,
                      encode_to_stream_VkAttachmentReference2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSubpassDescription2,
                      encode_to_stream_VkSubpassDescription2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSubpassDependency2, encode_to_stream_VkSubpassDependency2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSubpassBeginInfo, encode_to_stream_VkSubpassBeginInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSubpassEndInfo, encode_to_stream_VkSubpassEndInfoKHR)

#endif
#ifdef VK_KHR_external_fence_capabilities
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceExternalFenceInfo,
                      encode_to_stream_VkPhysicalDeviceExternalFenceInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExternalFenceProperties,
                      encode_to_stream_VkExternalFencePropertiesKHR)

#endif
#ifdef VK_KHR_external_fence
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkExportFenceCreateInfo,
                      encode_to_stream_VkExportFenceCreateInfoKHR)

#endif
#ifdef VK_KHR_external_fence_fd
void encode_to_stream_VkImportFenceFdInfoKHR(VkStructureType rootType,
                                            const VkImportFenceFdInfoKHR* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkFenceGetFdInfoKHR(VkStructureType rootType,
                                         const VkFenceGetFdInfoKHR* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_maintenance2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDevicePointClippingProperties,
                      encode_to_stream_VkPhysicalDevicePointClippingPropertiesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkRenderPassInputAttachmentAspectCreateInfo,
                      encode_to_stream_VkRenderPassInputAttachmentAspectCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkInputAttachmentAspectReference,
                      encode_to_stream_VkInputAttachmentAspectReferenceKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageViewUsageCreateInfo,
                      encode_to_stream_VkImageViewUsageCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPipelineTessellationDomainOriginStateCreateInfo,
                      encode_to_stream_VkPipelineTessellationDomainOriginStateCreateInfoKHR)

#endif
#ifdef VK_KHR_dedicated_allocation
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkMemoryDedicatedRequirements,
                      encode_to_stream_VkMemoryDedicatedRequirementsKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkMemoryDedicatedAllocateInfo,
                      encode_to_stream_VkMemoryDedicatedAllocateInfoKHR)

#endif
#ifdef VK_KHR_get_memory_requirements2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBufferMemoryRequirementsInfo2,
                      encode_to_stream_VkBufferMemoryRequirementsInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageMemoryRequirementsInfo2,
                      encode_to_stream_VkImageMemoryRequirementsInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageSparseMemoryRequirementsInfo2,
                      encode_to_stream_VkImageSparseMemoryRequirementsInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkMemoryRequirements2,
                      encode_to_stream_VkMemoryRequirements2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSparseImageMemoryRequirements2,
                      encode_to_stream_VkSparseImageMemoryRequirements2KHR)

#endif
#ifdef VK_KHR_image_format_list
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageFormatListCreateInfo,
                      encode_to_stream_VkImageFormatListCreateInfoKHR)

#endif
#ifdef VK_KHR_sampler_ycbcr_conversion
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSamplerYcbcrConversionCreateInfo,
                      encode_to_stream_VkSamplerYcbcrConversionCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSamplerYcbcrConversionInfo,
                      encode_to_stream_VkSamplerYcbcrConversionInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBindImagePlaneMemoryInfo,
                      encode_to_stream_VkBindImagePlaneMemoryInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImagePlaneMemoryRequirementsInfo,
                      encode_to_stream_VkImagePlaneMemoryRequirementsInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceSamplerYcbcrConversionFeatures,
                      encode_to_stream_VkPhysicalDeviceSamplerYcbcrConversionFeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSamplerYcbcrConversionImageFormatProperties,
                      encode_to_stream_VkSamplerYcbcrConversionImageFormatPropertiesKHR)

#endif
#ifdef VK_KHR_bind_memory2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBindBufferMemoryInfo,
                      encode_to_stream_VkBindBufferMemoryInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBindImageMemoryInfo,
                      encode_to_stream_VkBindImageMemoryInfoKHR)

#endif
#ifdef VK_KHR_maintenance3
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceMaintenance3Properties,
                      encode_to_stream_VkPhysicalDeviceMaintenance3PropertiesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDescriptorSetLayoutSupport,
                      encode_to_stream_VkDescriptorSetLayoutSupportKHR)

#endif
#ifdef VK_KHR_shader_subgroup_extended_types
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderSubgroupExtendedTypesFeatures,
                      encode_to_stream_VkPhysicalDeviceShaderSubgroupExtendedTypesFeaturesKHR)

#endif
#ifdef VK_KHR_vulkan_memory_model
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceVulkanMemoryModelFeatures,
                      encode_to_stream_VkPhysicalDeviceVulkanMemoryModelFeaturesKHR)

#endif
#ifdef VK_KHR_shader_terminate_invocation
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderTerminateInvocationFeatures,
                      encode_to_stream_VkPhysicalDeviceShaderTerminateInvocationFeaturesKHR)

#endif
#ifdef VK_KHR_buffer_device_address
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceBufferDeviceAddressFeatures,
                      encode_to_stream_VkPhysicalDeviceBufferDeviceAddressFeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBufferDeviceAddressInfo,
                      encode_to_stream_VkBufferDeviceAddressInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBufferOpaqueCaptureAddressCreateInfo,
                      encode_to_stream_VkBufferOpaqueCaptureAddressCreateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkMemoryOpaqueCaptureAddressAllocateInfo,
                      encode_to_stream_VkMemoryOpaqueCaptureAddressAllocateInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDeviceMemoryOpaqueCaptureAddressInfo,
                      encode_to_stream_VkDeviceMemoryOpaqueCaptureAddressInfoKHR)

#endif
#ifdef VK_KHR_pipeline_executable_properties
void encode_to_stream_VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR(
    VkStructureType rootType,
    const VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineInfoKHR(VkStructureType rootType,
                                       const VkPipelineInfoKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineExecutablePropertiesKHR(
    VkStructureType rootType,
    const VkPipelineExecutablePropertiesKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineExecutableInfoKHR(
                                                 VkStructureType rootType,
                                                 const VkPipelineExecutableInfoKHR* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkPipelineExecutableStatisticValueKHR(
    VkStructureType rootType,
    const VkPipelineExecutableStatisticValueKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineExecutableStatisticKHR(
    VkStructureType rootType,
    const VkPipelineExecutableStatisticKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineExecutableInternalRepresentationKHR(
    VkStructureType rootType,
    const VkPipelineExecutableInternalRepresentationKHR* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_shader_integer_dot_product
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderIntegerDotProductFeatures,
                      encode_to_stream_VkPhysicalDeviceShaderIntegerDotProductFeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderIntegerDotProductProperties,
                      encode_to_stream_VkPhysicalDeviceShaderIntegerDotProductPropertiesKHR)

#endif
#ifdef VK_KHR_synchronization2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkMemoryBarrier2, encode_to_stream_VkMemoryBarrier2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBufferMemoryBarrier2,
                      encode_to_stream_VkBufferMemoryBarrier2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageMemoryBarrier2,
                      encode_to_stream_VkImageMemoryBarrier2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDependencyInfo, encode_to_stream_VkDependencyInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSubmitInfo2, encode_to_stream_VkSubmitInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSemaphoreSubmitInfo,
                      encode_to_stream_VkSemaphoreSubmitInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkCommandBufferSubmitInfo,
                      encode_to_stream_VkCommandBufferSubmitInfoKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceSynchronization2Features,
                      encode_to_stream_VkPhysicalDeviceSynchronization2FeaturesKHR)

void encode_to_stream_VkQueueFamilyCheckpointProperties2NV(
    VkStructureType rootType,
    const VkQueueFamilyCheckpointProperties2NV* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCheckpointData2NV(VkStructureType rootType,
                                         const VkCheckpointData2NV* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_KHR_zero_initialize_workgroup_memory
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeatures,
                      encode_to_stream_VkPhysicalDeviceZeroInitializeWorkgroupMemoryFeaturesKHR)

#endif
#ifdef VK_KHR_copy_commands2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkCopyBufferInfo2, encode_to_stream_VkCopyBufferInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkCopyImageInfo2, encode_to_stream_VkCopyImageInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkCopyBufferToImageInfo2,
                      encode_to_stream_VkCopyBufferToImageInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkCopyImageToBufferInfo2,
                      encode_to_stream_VkCopyImageToBufferInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBlitImageInfo2, encode_to_stream_VkBlitImageInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkResolveImageInfo2, encode_to_stream_VkResolveImageInfo2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBufferCopy2, encode_to_stream_VkBufferCopy2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageCopy2, encode_to_stream_VkImageCopy2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageBlit2, encode_to_stream_VkImageBlit2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkBufferImageCopy2, encode_to_stream_VkBufferImageCopy2KHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageResolve2, encode_to_stream_VkImageResolve2KHR)

#endif
#ifdef VK_KHR_format_feature_flags2
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkFormatProperties3, encode_to_stream_VkFormatProperties3KHR)

#endif
#ifdef VK_KHR_maintenance4
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceMaintenance4Features,
                      encode_to_stream_VkPhysicalDeviceMaintenance4FeaturesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceMaintenance4Properties,
                      encode_to_stream_VkPhysicalDeviceMaintenance4PropertiesKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDeviceBufferMemoryRequirements,
                      encode_to_stream_VkDeviceBufferMemoryRequirementsKHR)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDeviceImageMemoryRequirements,
                      encode_to_stream_VkDeviceImageMemoryRequirementsKHR)

#endif
#ifdef VK_KHR_maintenance5
void encode_to_stream_VkPhysicalDeviceMaintenance5FeaturesKHR(
    VkStructureType rootType,
    const VkPhysicalDeviceMaintenance5FeaturesKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceMaintenance5PropertiesKHR(
    VkStructureType rootType,
    const VkPhysicalDeviceMaintenance5PropertiesKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderingAreaInfoKHR(VkStructureType rootType,
                                            const VkRenderingAreaInfoKHR* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkImageSubresource2KHR(VkStructureType rootType,
                                            const VkImageSubresource2KHR* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkDeviceImageSubresourceInfoKHR(
    VkStructureType rootType,
    const VkDeviceImageSubresourceInfoKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubresourceLayout2KHR(VkStructureType rootType,
                                             const VkSubresourceLayout2KHR* forMarshaling,
                                             uint8_t** ptr);

void encode_to_stream_VkPipelineCreateFlags2CreateInfoKHR(
    VkStructureType rootType,
    const VkPipelineCreateFlags2CreateInfoKHR* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkBufferUsageFlags2CreateInfoKHR(
    VkStructureType rootType,
    const VkBufferUsageFlags2CreateInfoKHR* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_ANDROID_native_buffer
void encode_to_stream_VkNativeBufferUsage2ANDROID(
                                                 VkStructureType rootType,
                                                 const VkNativeBufferUsage2ANDROID* forMarshaling,
                                                 uint8_t** ptr);

void encode_to_stream_VkNativeBufferANDROID(VkStructureType rootType,
                                           const VkNativeBufferANDROID* forMarshaling,
                                           uint8_t** ptr);

void encode_to_stream_VkSwapchainImageCreateInfoANDROID(
    VkStructureType rootType,
    const VkSwapchainImageCreateInfoANDROID* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDevicePresentationPropertiesANDROID(
    VkStructureType rootType,
    const VkPhysicalDevicePresentationPropertiesANDROID* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_transform_feedback
void encode_to_stream_VkPhysicalDeviceTransformFeedbackFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceTransformFeedbackFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceTransformFeedbackPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceTransformFeedbackPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineRasterizationStateStreamCreateInfoEXT(
    VkStructureType rootType,
    const VkPipelineRasterizationStateStreamCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_texture_compression_astc_hdr
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceTextureCompressionASTCHDRFeatures,
                      encode_to_stream_VkPhysicalDeviceTextureCompressionASTCHDRFeaturesEXT)

#endif
#ifdef VK_EXT_depth_clip_enable
void encode_to_stream_VkPhysicalDeviceDepthClipEnableFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceDepthClipEnableFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineRasterizationDepthClipStateCreateInfoEXT(
    VkStructureType rootType,
    const VkPipelineRasterizationDepthClipStateCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_inline_uniform_block
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceInlineUniformBlockFeatures,
                      encode_to_stream_VkPhysicalDeviceInlineUniformBlockFeaturesEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceInlineUniformBlockProperties,
                      encode_to_stream_VkPhysicalDeviceInlineUniformBlockPropertiesEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkWriteDescriptorSetInlineUniformBlock,
                      encode_to_stream_VkWriteDescriptorSetInlineUniformBlockEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDescriptorPoolInlineUniformBlockCreateInfo,
                      encode_to_stream_VkDescriptorPoolInlineUniformBlockCreateInfoEXT)

#endif
#ifdef VK_EXT_image_drm_format_modifier
void encode_to_stream_VkDrmFormatModifierPropertiesEXT(
    VkStructureType rootType,
    const VkDrmFormatModifierPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDrmFormatModifierPropertiesListEXT(
    VkStructureType rootType,
    const VkDrmFormatModifierPropertiesListEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceImageDrmFormatModifierInfoEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceImageDrmFormatModifierInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageDrmFormatModifierListCreateInfoEXT(
    VkStructureType rootType,
    const VkImageDrmFormatModifierListCreateInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageDrmFormatModifierExplicitCreateInfoEXT(
    VkStructureType rootType,
    const VkImageDrmFormatModifierExplicitCreateInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageDrmFormatModifierPropertiesEXT(
    VkStructureType rootType,
    const VkImageDrmFormatModifierPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDrmFormatModifierProperties2EXT(
    VkStructureType rootType,
    const VkDrmFormatModifierProperties2EXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDrmFormatModifierPropertiesList2EXT(
    VkStructureType rootType,
    const VkDrmFormatModifierPropertiesList2EXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_vertex_attribute_divisor
void encode_to_stream_VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkVertexInputBindingDivisorDescriptionEXT(
    VkStructureType rootType,
    const VkVertexInputBindingDivisorDescriptionEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineVertexInputDivisorStateCreateInfoEXT(
    VkStructureType rootType,
    const VkPipelineVertexInputDivisorStateCreateInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_pipeline_creation_feedback
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPipelineCreationFeedbackCreateInfo,
                      encode_to_stream_VkPipelineCreationFeedbackCreateInfoEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPipelineCreationFeedback,
                      encode_to_stream_VkPipelineCreationFeedbackEXT)

#endif
#ifdef VK_EXT_fragment_density_map
void encode_to_stream_VkPhysicalDeviceFragmentDensityMapFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceFragmentDensityMapFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceFragmentDensityMapPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceFragmentDensityMapPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkRenderPassFragmentDensityMapCreateInfoEXT(
    VkStructureType rootType,
    const VkRenderPassFragmentDensityMapCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_scalar_block_layout
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceScalarBlockLayoutFeatures,
                      encode_to_stream_VkPhysicalDeviceScalarBlockLayoutFeaturesEXT)

#endif
#ifdef VK_EXT_subgroup_size_control
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceSubgroupSizeControlFeatures,
                      encode_to_stream_VkPhysicalDeviceSubgroupSizeControlFeaturesEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceSubgroupSizeControlProperties,
                      encode_to_stream_VkPhysicalDeviceSubgroupSizeControlPropertiesEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPipelineShaderStageRequiredSubgroupSizeCreateInfo,
                      encode_to_stream_VkPipelineShaderStageRequiredSubgroupSizeCreateInfoEXT)

#endif
#ifdef VK_EXT_tooling_info
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceToolProperties,
                      encode_to_stream_VkPhysicalDeviceToolPropertiesEXT)

#endif
#ifdef VK_EXT_provoking_vertex
void encode_to_stream_VkPhysicalDeviceProvokingVertexFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceProvokingVertexFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceProvokingVertexPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceProvokingVertexPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineRasterizationProvokingVertexStateCreateInfoEXT(
    VkStructureType rootType,
    const VkPipelineRasterizationProvokingVertexStateCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_line_rasterization
void encode_to_stream_VkPhysicalDeviceLineRasterizationFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceLineRasterizationFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceLineRasterizationPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceLineRasterizationPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineRasterizationLineStateCreateInfoEXT(
    VkStructureType rootType,
    const VkPipelineRasterizationLineStateCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_index_type_uint8
void encode_to_stream_VkPhysicalDeviceIndexTypeUint8FeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceIndexTypeUint8FeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_extended_dynamic_state
void encode_to_stream_VkPhysicalDeviceExtendedDynamicStateFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceExtendedDynamicStateFeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_host_image_copy
void encode_to_stream_VkPhysicalDeviceHostImageCopyFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceHostImageCopyFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceHostImageCopyPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceHostImageCopyPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkMemoryToImageCopyEXT(VkStructureType rootType,
                                            const VkMemoryToImageCopyEXT* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkImageToMemoryCopyEXT(VkStructureType rootType,
                                            const VkImageToMemoryCopyEXT* forMarshaling,
                                            uint8_t** ptr);

void encode_to_stream_VkCopyMemoryToImageInfoEXT(
                                                VkStructureType rootType,
                                                const VkCopyMemoryToImageInfoEXT* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkCopyImageToMemoryInfoEXT(
                                                VkStructureType rootType,
                                                const VkCopyImageToMemoryInfoEXT* forMarshaling,
                                                uint8_t** ptr);

void encode_to_stream_VkCopyImageToImageInfoEXT(
                                               VkStructureType rootType,
                                               const VkCopyImageToImageInfoEXT* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkHostImageLayoutTransitionInfoEXT(
    VkStructureType rootType,
    const VkHostImageLayoutTransitionInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkSubresourceHostMemcpySizeEXT(
    VkStructureType rootType,
    const VkSubresourceHostMemcpySizeEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkHostImageCopyDevicePerformanceQueryEXT(
    VkStructureType rootType,
    const VkHostImageCopyDevicePerformanceQueryEXT* forMarshaling, uint8_t** ptr);

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkSubresourceLayout2KHR,
                      encode_to_stream_VkSubresourceLayout2EXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkImageSubresource2KHR,
                      encode_to_stream_VkImageSubresource2EXT)

#endif
#ifdef VK_EXT_shader_demote_to_helper_invocation
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceShaderDemoteToHelperInvocationFeatures,
                      encode_to_stream_VkPhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT)

#endif
#ifdef VK_EXT_texel_buffer_alignment
void encode_to_stream_VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT* forMarshaling, uint8_t** ptr);

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceTexelBufferAlignmentProperties,
                      encode_to_stream_VkPhysicalDeviceTexelBufferAlignmentPropertiesEXT)

#endif
#ifdef VK_EXT_device_memory_report
void encode_to_stream_VkPhysicalDeviceDeviceMemoryReportFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceDeviceMemoryReportFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceMemoryReportCallbackDataEXT(
    VkStructureType rootType,
    const VkDeviceMemoryReportCallbackDataEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkDeviceDeviceMemoryReportCreateInfoEXT(
    VkStructureType rootType,
    const VkDeviceDeviceMemoryReportCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_robustness2
void encode_to_stream_VkPhysicalDeviceRobustness2FeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceRobustness2FeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceRobustness2PropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceRobustness2PropertiesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_custom_border_color
void encode_to_stream_VkSamplerCustomBorderColorCreateInfoEXT(
    VkStructureType rootType,
    const VkSamplerCustomBorderColorCreateInfoEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceCustomBorderColorPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceCustomBorderColorPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceCustomBorderColorFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceCustomBorderColorFeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_private_data
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDevicePrivateDataFeatures,
                      encode_to_stream_VkPhysicalDevicePrivateDataFeaturesEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkDevicePrivateDataCreateInfo,
                      encode_to_stream_VkDevicePrivateDataCreateInfoEXT)

DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPrivateDataSlotCreateInfo,
                      encode_to_stream_VkPrivateDataSlotCreateInfoEXT)

#endif
#ifdef VK_EXT_pipeline_creation_cache_control
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDevicePipelineCreationCacheControlFeatures,
                      encode_to_stream_VkPhysicalDevicePipelineCreationCacheControlFeaturesEXT)

#endif
#ifdef VK_EXT_graphics_pipeline_library
void encode_to_stream_VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceGraphicsPipelineLibraryFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceGraphicsPipelineLibraryPropertiesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkGraphicsPipelineLibraryCreateInfoEXT(
    VkStructureType rootType,
    const VkGraphicsPipelineLibraryCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_ycbcr_2plane_444_formats
void encode_to_stream_VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceYcbcr2Plane444FormatsFeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_image_robustness
DEFINE_ALIAS_FUNCTION(encode_to_stream_VkPhysicalDeviceImageRobustnessFeatures,
                      encode_to_stream_VkPhysicalDeviceImageRobustnessFeaturesEXT)

#endif
#ifdef VK_EXT_image_compression_control
void encode_to_stream_VkPhysicalDeviceImageCompressionControlFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceImageCompressionControlFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkImageCompressionControlEXT(
                                                  VkStructureType rootType,
                                                  const VkImageCompressionControlEXT* forMarshaling,
                                                  uint8_t** ptr);

void encode_to_stream_VkImageCompressionPropertiesEXT(
    VkStructureType rootType,
    const VkImageCompressionPropertiesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_4444_formats
void encode_to_stream_VkPhysicalDevice4444FormatsFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDevice4444FormatsFeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_primitive_topology_list_restart
void encode_to_stream_VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDevicePrimitiveTopologyListRestartFeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_extended_dynamic_state2
void encode_to_stream_VkPhysicalDeviceExtendedDynamicState2FeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceExtendedDynamicState2FeaturesEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_color_write_enable
void encode_to_stream_VkPhysicalDeviceColorWriteEnableFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceColorWriteEnableFeaturesEXT* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkPipelineColorWriteCreateInfoEXT(
    VkStructureType rootType,
    const VkPipelineColorWriteCreateInfoEXT* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_GOOGLE_gfxstream
void encode_to_stream_VkImportColorBufferGOOGLE(
                                               VkStructureType rootType,
                                               const VkImportColorBufferGOOGLE* forMarshaling,
                                               uint8_t** ptr);

void encode_to_stream_VkImportBufferGOOGLE(VkStructureType rootType,
                                          const VkImportBufferGOOGLE* forMarshaling, uint8_t** ptr);

void encode_to_stream_VkCreateBlobGOOGLE(VkStructureType rootType,
                                        const VkCreateBlobGOOGLE* forMarshaling, uint8_t** ptr);

#endif
#ifdef VK_EXT_image_compression_control_swapchain
void encode_to_stream_VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT(
    VkStructureType rootType,
    const VkPhysicalDeviceImageCompressionControlSwapchainFeaturesEXT* forMarshaling,
    uint8_t** ptr);

#endif